version: "2"
services:
  sonarqube:
    image: sonarqube:8.4.0-community
    ports:
      - "19099:9000"
    networks:
      - sonarnet
    volumes:
      - ./plugins/sonar-c-plugin-1.3.3.2051.jar:/opt/sonarqube/extensions/plugins/sonar-c-plugin-1.3.3.2051.jar
      - ./plugins/sonar-cxx-plugin-1.3.3.2051.jar:/opt/sonarqube/extensions/plugins/sonar-cxx-plugin-1.3.3.2051.jar
      - ./plugins/checkstyle-sonar-plugin-8.40.jar:/opt/sonarqube/extensions/plugins/checkstyle-sonar-plugin-8.40.jar
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar

  db:
    image: postgres:11.1
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql_data:
