version: '2'
services:
  code-server-wangzy:
    build: .
    image: code-server-wangzy
    container_name: vscode-container-wangzy
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
      - "./workspace:/home/wangzy/workspace"
      - "./entrypoint.sh:/usr/bin/entrypoint.sh"
    ports:
      - "9099:8080"
      - "443:443"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    user: wangzy
    stdin_open: true
    tty: true

