version: '2.0'
services:
  registry:
    image: registry
    container_name: registry
    restart: unless-stopped
    ports:
      - 35000:5000
    volumes:
      - /data/registry:/var/lib/registry
      - ./registry-config/config.yml:/etc/docker/registry/config.yml

  ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    ports:
      - 28080:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://localhost:35000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry

