version: '2'

services:
    richfilemanager:
        image: scratch_flask:latest
        container_name: richfilemanager-flask
        restart: unless-stopped
        ports:
            - "18888:80"
        volumes:
            - "/etc/timezone:/etc/timezone"
            - "/etc/localtime:/etc/localtime"
            - "./default.conf:/etc/nginx/conf.d/default.conf"
            - "./entrypoint.d/30-start-gunicorn.sh:/docker-entrypoint.d/30-start-gunicorn.sh"
            - "./RichFilemanager-Python3Flask-master:/opt"
        user: root

